main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name="index"),
]

pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('api/', include('menu.api_urls')),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models


class Pizza(models.Model):
    nom = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    prix = models.FloatField(default=0)
    vegetarienne = models.BooleanField(default=False)

    def __str__(self):
        return self.nom

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def index(request):
    return render(request, 'main/index.html')

menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Pizza
from django.core import serializers

# Create your views here.


def index(request):
    pizzas = Pizza.objects.all().order_by('prix')
    return render(request, 'menu/index.html', {'pizzas': pizzas})


def api_get_pizzas(request):
    pizzas = Pizza.objects.all().order_by('prix')
    json = serializers.serialize("json", pizzas)
    return HttpResponse(json)

main/templates/main/index.html
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    <title>Page principal</title>
</head>
<body>
    <div class="centered">
        <img class="logo" src="{% static 'main/images/main_logo.png' %}">
        <a href="{% url 'menu:index' %}">Voir le menu</a>
    </div>

</body>
</html>

menu/templates/menu/index.html
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
    <title>Menu des pizzas</title>
</head>
<body>
    <a href="{% url 'main:index' %}"><img class="logo" src="{% static 'menu/images/small_logo.png' %}"></a>
    <div class="menu-title">
        <h1>Les pizzas</h1>
    </div>

    <div class="menu-list">
        {% for pizza in pizzas %}
            <div class="menu-list-item">
                <span class="menu-list-title">{{pizza.nom}}</span>
                <span class="menu-list-price">{{pizza.prix | floatformat:2}} $</span>
                <span class="menu-list-ingredient">{{pizza.ingredients}}</span>
                {% if pizza.vegetarienne %}
                    <span class="menu-list-vegetarienne">VÉGÉTARIENNE</span>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    
</body>
</html>